version: '3'
services:
  chat-app:
    build: ./chat
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    depends_on:
      - chat-server
    
  chat-server:
    build: ./server
    ports:
      - "4100:4100"
    command: ["node", "index.js"]